version: '3'
services:
  crawler:
    build: .
    container_name: crawler
  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"
    environment:
      - SPLASH_MAX_TIMEOUT=3600  # Set the maximum timeout for requests
      - ENABLE_ADBLOCK=1         # Enable adblock to reduce ads in rendered pages
    restart: unless-stopped
  postgres:
    container_name: gen3-crawler-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gen3_crawler
    ports:
      - "5432:5432"